#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2020 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "dracula"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false

[[custom_plugins]]
  repo = "dracula/vim"
  name = "dracula"
  merged = false

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
name = "lang#java"

[[layers]]
  name = "lsp"
  filetypes = [
    "java"
  ]
  [layers.override_cmd]
    java = [
    "java",
    "-javaagent:/Users/danielmiralles/Tools/lombok.jar",
    "-Xbootclasspath/p:/Users/danielmiralles/Tools/lombok.jar"
    "-Declipse.application=org.eclipse.jdt.ls.core.id1",
    "-Dosgi.bundles.defaultStartLevel=4",
    "-Declipse.product=org.eclipse.jdt.ls.core.product",
    "-Dlog.protocol=true",
    "-Dlog.level=NONE",
    "-noverify",
    "-Xmx1G",
    "-Dfile.encoding=UTF-8",
    "-jar",
    "/Users/danielmiralles/lsp/eclipse.jdt.ls/plugins/org.eclipse.equinox.launcher_1.5.600.v20191014-2022.jar",
    "-configuration",
    "/Users/danielmiralles/lsp/eclipse.jdt.ls/config_mac",
    "-data",
    "/Users/danielmiralles/.cache/javalsp"
    ]

[[layers]]
name = "fzf"

[[layers]]
name = "checkers"
show_cursor_error = false

[[layers]]
  name = "gtags"
  gtagslabel = "ctags"

[[layers]]
  name = "colorscheme"

[[layers]]
  name = "git"

[[layers]]
  name = "github"

[[layers]]
  name = "debug"
